### ISSUE TITLE
Primary key may cause hotspots

### ISSUE THREAD

**Issue by adelapena** [javanotes/weblogs#1]
First of all, congrats for the project, it looks very interesting.

Reading [your article is DZone](https://dzone.com/articles/full-text-searchable-log-repository-using-cassandr) I see that your schema for events is:

```
CREATE TABLE data_points (
    app_id text,
    event_ts timeuuid,
    level text,
    log_text text,
    lucene text,
    PRIMARY KEY (app_id, event_ts)
) WITH CLUSTERING ORDER BY (event_ts DESC)
```

If I'm right, such primary key could produce excessively wide rows and/or hotspots. All the events of each application will be stored in a single storage engine row, whereas it's recommended not to store more than ~100MB per partition, so it could be problematic if an application produces millions or records. Additionally, the eventually ultra-wide rows will be stored in a single node (and its replicas), so all the traffic of an application will be directed to this single node, which could become a hotspot.

Alternatively, according to [this guide about how to model time series](http://www.datastax.com/dev/blog/advanced-time-series-with-cassandra) and this [other newer one](https://academy.datastax.com/demos/getting-started-time-series-data-modeling), you could use this schema to prevent both ultra-wide rows and hotspots:

```
CREATE TABLE data_points (
    app_id text,
    time_bucket text,
    event_ts timeuuid,
    level text,
    log_text text,
    lucene text,
    PRIMARY KEY ((app_id, time_bucket), event_ts)
) WITH CLUSTERING ORDER BY (event_ts DESC)
```

What do you think? Does it make sense?

**Comment by javanotes** [comment]
I agree that keeping a single partition key, as I have approached, may not be a good idea. In fact, this is one thing that is on my mind from the onset! However, from my primary use case perspective, I would want to simply search logs within a time frame, and the only thing I should be aware of is, probably, which application log I want to look. 

Now, if I provide any other partition key candidate, that information will needed upfront for any user query. Even if I make the 'time_bucket' to correspond (somehow!) with the 'event_ts' time component, or use a logger_name as a part of the partition key, then also there will be some challenge while performing pagination queries; using token() function tricks along with allow filtering, to restrict result. 

Anyway, thanks for your response, and I do have the issue in my mind to look into. And thank you and your team, for providing such an elegant open sourced plugin for Cassandra.

**Comment by javanotes** [comment]
Though you have closed the issue, as promised, I went on trying for a composite partition key modeled design. The solution eventually is not trivial per my use case, but respecting the nature of Cassandra I went ahead. Some discussions [here](http://hotjavanotes.blogspot.in/2015/12/my-adventures-with-cassandra.html)
